### ISSUE TITLE
Solution for OpenSLL not found in Boost when compiling.

### ISSUE THREAD

**Issue by lawrnce** [socketio/socket.io-client-cpp#101]
I ran into this problem even after I linked open ssl to CMAKE using `-OPENSSL_ROOT_DIR` 

When compiling this error shows up 

`/usr/local/Cellar/boost/1.60.0_1/include/boost/asio/ssl/detail/openssl_types.hpp:19:10: fatal error: 'openssl/conf.h' file not found
#include <openssl/conf.h>`

make sure you have open ssl install via brew and run the cmake cmd like this 

`cmake -DBOOST_INCLUDEDIR=/usr/local/Cellar/boost/1.60.0_1/include -DBOOST_LIBRARYDIR=/usr/local/Cellar/boost/1.60.0_1/lib -DBOOST_VER:STRING=1.60.0 -DCMAKE_CXX_FLAGS="-I/usr/local/opt/openssl/include" -DCMAKE_MODULE_LINKER_FLAGS="-L/usr/local/opt/openssl/lib" ./`

then run `make install`

Hopes this helps!

**Comment by tdarbinyan** [comment]
Thank you! I wasted several hours trying to fix it, but only your solution helped. Here is the command that worked for me on Windows
cmake -DBOOST_INCLUDEDIR=C:/BOOST/include -DBOOST_LIBRARYDIR=C:/BOOST/lib -DBOOST_VER:STRING=1.82.0 -DCMAKE_CXX_FLAGS=-IC:/OpenSSL-Win64/include -DCMAKE_MODULE_LINKER_FLAGS=-LC:/OpenSSL-Win64/lib ./
