### ISSUE TITLE
remove boost lib install

### ISSUE THREAD

**Issue by DraconPern** [socketio/socket.io-client-cpp#115]
The last few lines of cmakelists.txt installs the boost libraries.  At least on Windows, if there are release and debug versions of boost libraries, the ${Boost_LIBRARIES} macro has 'optimized' and 'debug'.  With the command install(FILES ${Boost_LIBRARIES}, the command thinks 'optimized' is a real file.  I think it is better if that install command is removed, since the boost libs should be linked anyways instead of installed.

**Comment by jmigual** [comment]
Removed boost dependency on af68bf3067ab45dc6a53261284e0da9afd21b636
