### ISSUE TITLE
Access violation exception when using socketio-client-c++ and boost asio io_service

### ISSUE THREAD

**Issue by octane92** [socketio/socket.io-client-cpp#118]
I'm trying to use io_service from boost asio library (1.61) with socketio-client-c++, but my code throws an access violation exception, and after hours of debugging I could'nt figure out what is the cause. The exception is thrown at the following location in win_mutex.hpp:

```
void lock()
{
 -> ::EnterCriticalSection(&crit_section_);
}
```

The code is very simple:

```
int main(int argc, char* argv[]) {
    boost::asio::io_service io_service;
    auto io_service_work = std::make_shared<boost::asio::io_service::work>      (io_service);

    sio::client client_;
    client_.connect("http://localhost:1337");

    // io_service.run();
}
```

I want to use io_service from main, and socketio also uses an io_service internally, which might be the cause of the problem.

You can download the full project with socketio source and binary included here: https://drive.google.com/open?id=0ByS95lLWpDcQODFQaWZnX2lmajA

**Comment by mscofield0** [comment]
Each spawned `asio::io_service` is distinct from each other. There is an issue (#390) opened by me to allow providing a custom `io_service` to `sio::client`. Mark this as closed please.
