### ISSUE TITLE
Serialize JSON data

### ISSUE THREAD

**Issue by ryanosukl** [socketio/socket.io-client-cpp#119]
I am having some issues in identifying how to send JSON using the emit function.

My expected end result is a request structured as such:
std::string json = " {\"method\":\"get\",\"headers\":{},\"data\":{},\"url\":\"/subscribe\"}"';
and then (shortened for ease):
emit("get",json)

I have attempted to create a string and pass this as a binary value, however I wish for this to be sent as an object, how can I do so?

**Comment by ryanosukl** [comment]
I have tried this approach also;
auto t = string_message::create("bar");
auto m = object_message::create();
a.get()->get_map()->insert("foo",bar);

With no success

**Comment by DraconPern** [comment]
json is always text, there are no binary value and no object.  You'll have to do the conversion to say base64 yourself.

**Comment by ryanosukl** [comment]
The problem was solved by generating an array of key value pairs as this is what the library expects.
