### ISSUE TITLE
Exception in static-lib compilation mode caused by possible interference with boost::asio::io_service instance.

### ISSUE THREAD

**Issue by blaze1st** [socketio/socket.io-client-cpp#120]
http://stackoverflow.com/questions/39772075/differences-between-staticlib-and-dll-compilation-in-vs2015-entercriticalsectio

**Comment by blaze1st** [comment]
Please find a test package with 3 VS2015 solutions in the ZIP file:
http://ginf.hu/testpkg2.zip

Each solutions consist of 3 project (boost_system, siotest, and a library which either consists the mock sio lib, the websocket lib or the full socketio lib).

In each solution, a boost io_service is instantiated in the main function, and a client (which also instantiates an io_service through its constructor) is created, then the connect function of the client is called, which posts a function into the lib's io_service via dispatch.

The mock and the websocket based implementation works, while the socketio version results in unhandled exception, possible ODR violation. 

Any help is welcome in locating the issue.

**Comment by DraconPern** [comment]
Stack trace?

**Comment by DraconPern** [comment]
So... I see multiple problems... 

You have a boost_system project, not sure what that is.  Did you follow the build instruction in boost?  

You defined #define BOOST_ALL_NO_LIB even though you are linking against I guess some code in boost_system.  That's a conflict.

You have modified the library by making an extra file called dll.h and declaring something called SocketIODll and then declaring your c++ constructor and member functions to be __declspec( dllexport ).  That's a terrible idea.  Not sure what you are trying to do there.  You should probably read up on c++ and dll export support.

Please rework your code to use the non-modified version of the library.

**Comment by blaze1st** [comment]
BOOST_ALL_NO_LIB is defined so that no auto-linking is performed by boost, and NO, we are not linking against any boost library, the source is self-contained. Boost_system is included as source code, and compiled from source in this project. No conflict here.

If you check, SocketIODll is defined as an empty macro in case you compile it to be a static library (this is the case when the issue occurrs). DllExport only used when compiling in Dll mode, which in turn resolves the problem, so anything dllexport does is hiding the problem, not causing. No conflict here.

When you compile the socketio project ot a static library, the code is basically unmodified, because the macros do not change it at all.

**Comment by DraconPern** [comment]
I made a cmake project using the supported build methods and got no crash.  See attached.
[test.zip](https://github.com/socketio/socket.io-client-cpp/files/535653/test.zip)

**Comment by blaze1st** [comment]
As I see, it downloads boost 1_61. What I have in the test package uses no external source, it is a self-contained project file, which works if compiled in a single project and dll, and it does not work if compiling socketIO into a static lib.

We have found quite a lot of ways to hide the problem, without locating the real issue. Some more detail on the issue:
http://stackoverflow.com/questions/39772075/boost-asio-if-condition-evaluated-differently-in-static-lib-and-dll-compilations

Our aim is to find the cause of the issue, so that it can be guarantied that it does not happen in any project configuration.

So the code in testpkg2.zip is purely for testing purposes, but should enable the compilation of socketio without any external library, as the required boost source files are included and compiled according to the project configuration.

**Comment by wnpllrzodiac** [comment]
i met the same problem too.confused me for several days.crash when app exit.heap check error.asio crash

**Comment by jmigual** [comment]
Hi, the boost library is no longer required as of af68bf3067ab45dc6a53261284e0da9afd21b636
