### ISSUE TITLE
CMake 2.8 For Ubuntu 14.04

### ISSUE THREAD

**Issue by JustSpiffy** [socketio/socket.io-client-cpp#121]
Is it possible to adjust the CMake file to support Ubuntu 14.04 which runs CMake 2.8. The only major API change you're enforcing is `target_include_directories` which can easily be replaced with `target_properties(target PROPERTIES COMPILE_FLAGS ${INCLUDE_DIRS})` or just `include_directories` (which is understandably forceful.)

**Comment by JustSpiffy** [comment]
Actually, your cmake file is supported by 2.8.11 and 14.04 has 2.8.12, could you lower the cmake requirement to 2.8.11? I would like to use the project as a submodule with an automated cmake build.

**Comment by jmigual** [comment]
Hi, per https://hsf-training.github.io/hsf-training-cmake-webpage/07-commonproblems/index.html we raised the CMake minimum version to 3.4 now.
