### ISSUE TITLE
object_message how to constructor ! ! ! !

### ISSUE THREAD

**Issue by liwuking** [socketio/socket.io-client-cpp#127]
object_message *message1 = new object_message(1);

error: No matching constructor for initialization of 'sio::object_message'

**Comment by getnamo** [comment]
the format is sio::object_message::create()

I've added some examples for formulating raw c++ examples here: https://github.com/getnamo/socketio-client-ue4#alternative-raw-c-complex-message-using-siomessage. Ignore the ue4 specific stuff (FString etc).

**Comment by liwuking** [comment]
@getnamo  thank you
