### ISSUE TITLE
Is it possible to make a HTTPS SSL socket.io connection?

### ISSUE THREAD

**Issue by cewh** [socketio/socket.io-client-cpp#13]
Thanks.

**Comment by melode11** [comment]
Hi, For this version , No way is to support SSL connection.
I may enable it in future.

**Comment by cewh** [comment]
Thanks for the response.

**Comment by melode11** [comment]
Already start to develop 
c005a8792d8864788d2ea30e01ff944389c992fa

**Comment by melode11** [comment]
Hi, I have supported TLS in tag 1.4.0
c617682373420428d82190aa68efa749f938ad1f
For this version, the secured or unsecured client is decided compile time by macro `SIO_TLS`.
To use:
all after you've installed openssl , 
Use cmake target `sioclient_tls` or compile by yourself with `SIO_TLS` macro.
