### ISSUE TITLE
Console example stuck in lock

### ISSUE THREAD

**Issue by mdeforge** [socketio/socket.io-client-cpp#14]
int Participants never gets incremented after entering Nickname causing "if ( participants<0)" to evaluate true and put the program in an eternal lock with "_cond.wait ( _lock )".

Trying to tinker with it to get it to work but not having much success. Pretty new to this stuff. My Node server is only receiving user connected/disconnected events. If I'm suppose to see things like "login" and "add user" I'm definitely not seeing those either. Probably due to the aforementioned issue.

**Comment by mdeforge** [comment]
I didn't checkout and build the chat example from socket.io. Nevermind.

**Comment by melode11** [comment]
Hi, the wait condition is to ensure the login is succeed.
Indeed I have met the same issue before: If you're using incompatible version of socket.io and its modules, the broadcast will not work.(In my case latest socket.io and an older socket.io-adapter)
