### ISSUE TITLE
Emit Binary conversion error while using std::make_shared<std::string>( Foo )

### ISSUE THREAD

**Issue by mdeforge** [socketio/socket.io-client-cpp#15]
This is almost verbatim from the README.

char buf[100];
current_socket->emit ( "bintest", std::make_shared<std::string>(&buf, 100) );

I get: Error	1	error C2664: 'void sio::socket::emit(const std::string &,const sio::message::list &,const std::function<void (const sio::message::ptr &)> &)' : cannot convert argument 2 from 'std::shared_ptr<std::string>' to 'const sio::message::list &'	C:\Libraries\socket.io-client-cpp\examples\Console\main.cpp	90

**Comment by mdeforge** [comment]
I noticed in sio_socket.h that void emit has two default parameters. I don't think this is wise. If I specify a second parameter, who is to say which parameter I've specified? The second or third?

A second look at the error message above told me it was looking for the second parameter when I was trying to give it the third. I set the second parameter to nullptr and the third to the make_shared and the error went away. However, now I'm getting:

cannot convert argument 1 from 'char (*)[100]' to 'const std::basic_string<char,std::char_traits<char>,std::allocator<char>> &'

Still tinkering.

**Comment by melode11** [comment]
```C++
char buf[100];
current_socket->emit ( "bintest",   std::make_shared<const std::string>(&buf, 100));
```
I guess maybe in some compiler, the conversion constructor for share_ptr<const string> can not work for shared_ptr<string> .

**Comment by melode11** [comment]
Reason for Two default values is I was trying to keep the backward compatibility: the unified emit function should be able to called with all following forms: 
```
emit(event);
emit(event,string);
emit(event,binary);
emit(event,message);
emit(event,string,ack);
emit(event,binary,ack);
emit(event,message,ack);
```
And for default values, your second argument will always replace the second default value, won't be the third one.

**Comment by mdeforge** [comment]
I'm using Visual Studio 2013 (v120). Do you have any recommendations for a workaround?

**Comment by mdeforge** [comment]
PS: Making it const did not work. Tried that as well.

**Comment by melode11** [comment]
Did you tried my code in the 3rd post.

**Comment by melode11** [comment]
I'll test and fix it later today.

**Comment by melode11** [comment]
I have tested with clang, compile succeed if I put the `const` qualifier just in my first post.
But if your problem remains, can you try the `tls` branch to see if that fix your problem (I did some optimize). 
4f2e5d7b03837c5b88b0d09baeed6d5dc8c82203

**Comment by mdeforge** [comment]
That's so weird, the tls branch still doesn't work. If it helps, here's my source: http://pastebin.com/GtLYu6vZ I basically took the Console demo, stripped it down, and tried binary emits.

Not sure if you have Visual Studio 2013 installed, but if you'd like I can zip up my project for you. Maybe there's something in the project settings?

**Comment by melode11** [comment]
Do not need to send me project. I'll test it in vs 2013 myself tomorrow.

**Comment by mdeforge** [comment]
This works:

[code]
current_socket->emit ( "bintest", std::make_shared<std::string> ( "teststring" ) );
[/code]

Apparently, passing a char array by reference and including the size doesn't work. Good enough for my purposes, but the README should be updated.

**Comment by melode11** [comment]
This is not the proper way to send a binary.
If you're making `std::string` with a binary, you HAVE TO pass the size, otherwise your binary will be cut from the middle.

**Comment by melode11** [comment]
Hi,there.

I have tested in my VS 2013 community at Win8.1.

the code:
```C++
char buf[100];
current_socket->emit ( "bintest",   std::make_shared<const std::string>(&buf, 100));
```
works fine on `master` branch.

and your original code without `const` qualifier:
```C++
char buf[100];
current_socket->emit ( "bintest",   std::make_shared<std::string>(&buf, 100));
```
Not works on `master` branch but works on `tis` branch.

Could you please clean your project and try the first code block at the top again?

**Comment by mdeforge** [comment]
Just saw your message on the proper way to send a string. I haven't seen the side effects of that yet, but I'll take your word for it. Is it possible to send a integer via binary? I haven't been able to figure that one out yet. Didn't want to make a new issue, lol.

**Comment by melode11** [comment]
Hi, if you're making `std::string` with code:
```C++
std::string binary( "teststring" )
```
You are actually making a common string with c string,which is actually an array of chars ending with 0 in memory:
```
['t','e','s','t','s','t','r','i','n','g',0]
```
The `std::string` constructor will cut the string when it meets 0, so you get your "teststring" in `std::string`

But if you want to create real binary data without pass size like:
```C++
//real binary will be made up with values between 0-255 in any position.
//this is just a example
char buf = {'a','b','c',0,'d','e','f'}; 
std::string binary(buf)
```
the `std::string` constructor also cut the string when it meets 0, you're end up with "abc" in this case,  to create `std::string` with content "abc\0def" ,you have to pass the size 7.

**Comment by melode11** [comment]
About sending integers, suppose you need to send 0-9 in a buffer,just:
```C++
char buf[] = {0,1,2,3,4,5,6,7,8,9}; 
current_socket->emit ( "bintest",   std::make_shared<const std::string>(buf, 10));
```
