### ISSUE TITLE
wss and tls with socket.io-client-cpp

### ISSUE THREAD

**Issue by zglozman** [socketio/socket.io-client-cpp#156]
I am trying to establish a connection to a webserver that need sni extension.  where would i go about adding it ? right now it does not send the sni extension and as a result it simply fails to connect

**Comment by zglozman** [comment]
The libwebsocket dep needs to be updated, as they added sni by default. refresh of libwebsocket and it works

**Comment by tyym1314** [comment]
you can find project and lib in my github,socket_io with tls needs boost lib,openssl lib,i have complete this part of work,
the address:  https://github.com/tyym1314/socket.io-tls
