### ISSUE TITLE
Including sio_socket.h and compilation wit clang fails.

### ISSUE THREAD

**Issue by TimZaman** [socketio/socket.io-client-cpp#16]
```c++
In file included from /usr/local/include/sio_client.h:12:
/usr/local/include/sio_socket.h:73:31: error: expected ')'
        void emit(std::string const& name, message::list const& msglist = nullptr, std::function<void (message::ptr const&)> const& ack = nullptr);
                              ^
/usr/local/include/sio_socket.h:73:18: note: to match this '('
        void emit(std::string const& name, message::list const& msglist = nullptr, std::function<void (message::ptr const&)> const& ack = nullptr);
                 ^
/usr/local/include/sio_socket.h:73:24: error: non-friend class member 'string' cannot have a qualified name
        void emit(std::string const& name, message::list const& msglist = nullptr, std::function<void (message::ptr const&)> const& ack = nullptr);
                  ~~~~~^
/usr/local/include/sio_socket.h:73:24: error: field has incomplete type 'void'
3 errors generated.

** BUILD FAILED **

```

The issue resembles one (http://stackoverflow.com/questions/16759025/two-level-nested-c-class-works-with-gcc-but-fails-with-clang) where another compiler is possibly too permissive. Hence, a possible violation of _ (...) In such cases, the nested-name-specifier of the class-head-name of the definition shall not begin with a decltype-specifier._
Any ideas where this error might come from?

**Comment by TimZaman** [comment]
Also minor thing in your readme: 
`//emit event name only:
socket->emit("login");
//emit text
h.socket()->emit("add user", username);`
should be
`//emit event name only:
h.socket->emit("login");
//emit text
h.socket()->emit("add user", username);`

**Comment by melode11** [comment]
Thanks for reporting, but it seems OK on my clang.
Did you add c++11 options on your compiler.

**Comment by TimZaman** [comment]
Yes i did. Problem is that i always use cmake.
I found them problem. boost signals do not work together with those of qt. I had to specify no_keywords in cmake like this:
`ADD_DEFINITIONS(-DQT_NO_KEYWORDS) #makes boost signals work together with qt's when using cmake`
Excellent library, melode11, much appreated. *bows*

**Comment by Warren93** [comment]
I can't use the solution mentioned above because it appears to break Qt's signals. Also, I'm using gcc 4.8.5, not clang as in the original issue. Is there an alternative, straightforward fix for this compiler error?

**Comment by zhuzongzhi** [comment]
q

> Yes i did. Problem is that i always use cmake. I found them problem. boost signals do not work together with those of qt. I had to specify no_keywords in cmake like this: `ADD_DEFINITIONS(-DQT_NO_KEYWORDS) #makes boost signals work together with qt's when using cmake` Excellent library, melode11, much appreated. _bows_

qmake like that: DEFINES += QT_NO_KEYWORDS in *.pro file.

**Comment by MrJamesLZA** [comment]
> q
> 
> > Yes i did. Problem is that i always use cmake. I found them problem. boost signals do not work together with those of qt. I had to specify no_keywords in cmake like this: `ADD_DEFINITIONS(-DQT_NO_KEYWORDS) #makes boost signals work together with qt's when using cmake` Excellent library, melode11, much appreated. _bows_
> 
> qmake like that: DEFINES += QT_NO_KEYWORDS in *.pro file.

nice~this suggestion works! 
tks
