### ISSUE TITLE
I am not able to compile this client

### ISSUE THREAD

**Issue by PapiCZ** [socketio/socket.io-client-cpp#167]
Hello guys!
I am not able to compile this nice client because of following error:
```
/home/papi/development/obs-studio/UI/../socket.io-client-cpp/src/sio_socket.h:73:31: error: expected ‘)’ before ‘const’
void emit(std::string const& name, message::list const& msglist = nullptr, std::function<void (message::list const&)> const& ack = nullptr);
                      ^~~~~
```

It's a bug or I do something wrong?

EDIT// I am trying to compile it on Arch Linux

**Comment by HoseinHaqiqian** [comment]
how did you solve this?

**Comment by ulisesten** [comment]
> how did you solve this?

for me this worked: `add_definitions(-DQT_NO_KEYWORDS)` this makes the boost signals work
