### ISSUE TITLE
Client ssl certificate?

### ISSUE THREAD

**Issue by Riclas1** [socketio/socket.io-client-cpp#169]
Hi, 

Is there any documentation out, how connect a socket.io server with a cpp-client by checking server-side and client-side certificate. Or better first things first are there any support right now?

Thanks in advanced for your reply

Rico

**Comment by jianjunz** [comment]
Current implementation does not check server-side certificate. You can add a callback to `ctx` [here](https://github.com/socketio/socket.io-client-cpp/blob/master/src/internal/sio_client_impl.cpp#L568) if want to do so.

**Comment by Riclas1** [comment]
Thanks
