### ISSUE TITLE
No way to clear message::list?

### ISSUE THREAD

**Issue by mdeforge** [socketio/socket.io-client-cpp#17]
There is no public function to clear a message::list, and as far as I can tell, it's not automatically cleared after an emit that uses one. I've added in a clear for myself for now, but I feel as though this is an important feature, so I just wanted to make the suggestion. Maybe the message could pop off as they are sent? That's also an idea.

**Comment by melode11** [comment]
Hi, I'm not expecting `message::list` to be reused,  so I didn't put too many functionalities on it (which makes it like a std::vector).
For one time use, its content will be cleared in destructor.

**Comment by mdeforge** [comment]
What about getting rid of message::list and instructing users to create their own vector of type <message::ptr>? Seems kind of silly to create a type like message::list only to make it almost like vector. This would probably mess up your unified emit casting though. I know you're not expecting a list to be reused, but what about others?

**Comment by melode11** [comment]
`message::list` is for convenience and backward compatibility. See its conversion constructors.
I need 3 more `emit` interfaces to do the same thing without it.
