### ISSUE TITLE
How to use rooms

### ISSUE THREAD

**Issue by maximejimenez** [socketio/socket.io-client-cpp#172]
Hi,

I would like if it is possible to use rooms mechanism from Socket.IO with this implementation ?
Is it already supported ?
Does anyone have already done it ?

Thanks

**Comment by CollapsarLi** [comment]
Hi，
I also find this problem that the code don't provide rooms api.
Do you have solve the problem?

**Comment by maximejimenez** [comment]
Unfortunately, I ended up passing an extra ID and my server does the mapping between ids and socket.

**Comment by kaiavi** [comment]
Hey @maximejimenez 
I know that it's been a long time since you mentioned how you solved this issue, but I would appreciate some help.

> Unfortunately, I ended up passing an extra ID and my server does the mapping between ids and socket.

I am assuming you are passing some kind of identifier which server can use to identify the device. Could you tell me how you are passing this extra id?
