### ISSUE TITLE
SOCKET.IO 2.0 Compatibility

### ISSUE THREAD

**Issue by wedwards99** [socketio/socket.io-client-cpp#173]
Is there a plan to produce a version of this client to be compatible with socket.io 2.0 ?  Thanks!

**Comment by Parcley** [comment]
I thinl this issue is fixed?

**Comment by darrachequesne** [comment]
Yes, Socket.IO v2 is (and has always been) supported. Please see https://github.com/socketio/socket.io-client-cpp#compatibility-table.
