### ISSUE TITLE
'boost/lexical_cast.hpp' file not found

### ISSUE THREAD

**Issue by onezens** [socketio/socket.io-client-cpp#189]
git clone --recurse-submodules https://github.com/socketio/socket.io-client-cpp.git

#include <boost/lexical_cast.hpp>   exception: 'boost/lexical_cast.hpp' file not found

how to fix it?

**Comment by krishnastvSMSC** [comment]
Hello @onezens , am also facing same issue please let me know how to fix it..

Thank you
