### ISSUE TITLE
How to emit with TLS mode

### ISSUE THREAD

**Issue by cewh** [socketio/socket.io-client-cpp#19]
Thanks for including TLS.
I was having trouble emitting a simple message using the following code, I am probably doing something wrong;

	sio::client h;
	h.connect("https://127.0.0.1:1337");
	h.socket()->on("pong", (sio::socket::event_listener)&OnMessage);
	std::string test = "abc";
	h.socket()->emit("ping", test);

The server side does not obtain the emitted message "ping".
The console reports:

	[2015-06-01 14:55:26] [devel] endpoint constructor
	[2015-06-01 14:55:26] [devel] client constructor
	Close by reason:End by user
	Error: No active session
	[2015-06-01 14:55:26] [connect] Successful connection
	[2015-06-01 14:55:26] [connect] WebSocket Connection 127.0.0.1:1337 v-2 "WebSock
	et++/0.5.1" /socket.io/?EIO=4&transport=websocket&t=1433134526 101
	Connected.
	On handshake,sid:qefZuQzvE3KaklymAAAB,ping interval:25000,ping timeout60000
	Received Message type (Connect)

The part about "close by reason" is a cause of concern, I tried looking through the code but I'm not sure what would cause this.

**Comment by mdeforge** [comment]
I don't need this line in my project: h.socket()->on("pong", (sio::socket::event_listener)&OnMessage);

Have you seen the console example? I was able to modify that for my needs. Currently running C++ and Javascript clients with a Node.js server in between.

**Comment by melode11** [comment]
1. Your client object is stack allocated, so it'll destruct when run out of scope, that's why "end by user" happened.
You need to wait as long as the connection lives,see console demo.
2. The TLS feature is not controlled by the "https" in url, it is controlled by "SIO_TLS" macro at compile time.

**Comment by cewh** [comment]
I found the error in my code from your console example. I'll close the issue and thanks for the response!

**Comment by cewh** [comment]
I am working with the modified console example. The emit works and is received on the server side, I am also noticing a message every time I emit, I get the console message;

    ping exit,con is expired?0,ec:The I/O operation has been aborted because of either 
    a thread exit or an application request

The message comes from within client_impl::ping would this be related to ping interval or ping timeout setting?
