### ISSUE TITLE
excessively frequent reconnect attempts

### ISSUE THREAD

**Issue by oh3netid** [socketio/socket.io-client-cpp#20]
Hello, I've noticed that after about 78 or so failed connection attempts it starts reconnecting wildly with apparently no delay between attempts. I have seen this with default settings as well as with set_reconnect_delay set to 5000 and set_reconnect_delay_max to 10000. How do I prevent this?

Also, is there any way to suppress the [devel] output? Thanks!

**Comment by melode11** [comment]
Thanks,this is a bug of integer overflow while trying to cast the double value `pow(1.5,attempts)` to a unsigned int.
fixed in 2e94e799e264e5d4373d016569e8198c359d621d   tag 1.4.1

**Comment by melode11** [comment]
To suppress the [devel] output you can build in `Release` mode.

**Comment by oh3netid** [comment]
Yeah, I still need to see my own debug output (currently all getting lost in the deluge of [devel] output). So it would be nice to have a debug levels setting for the socket.io code. Guess that's a feature request.
