### ISSUE TITLE
Non-standard INSTALL paths?

### ISSUE THREAD

**Issue by ziocleto** [socketio/socket.io-client-cpp#201]
Any reason why the default usr/local/lib & co paths and CMAKE_INSTALL_PREFIX are not respected?

IE:
install(FILES ${ALL_HEADERS} 
    DESTINATION "${_CMAKE_CURRENT_LIST_DIR_}/**build**/include"
)

**Comment by limitedAtonement** [comment]
Did you make a pull request?

**Comment by ziocleto** [comment]
Nope I was just wondering why, I think it's a breaking code change for those with automatic build pipelines so it should be extensively evaluated, hence it was just a question of the reason of that particular decision?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client-cpp/commit/d353647b39c849da858aee041858d348c677dbcb.
