### ISSUE TITLE
error message on successful emit

### ISSUE THREAD

**Issue by cewh** [socketio/socket.io-client-cpp#21]
Hi, I am working with a modified console example with SIO_TLS. The emit works and is received on the server side, but I am noticing a message every time I emit, I also get the console message;

    ping exit,con is expired?0,ec:The I/O operation has been aborted because of either 
    a thread exit or an application request

The message comes from within client_impl::ping would this be related to ping interval or ping timeout setting? Thanks!

**Comment by melode11** [comment]
Hi, this is a normal case, the ping is for keeping the connection alive, the ping timer will be cancelled for a round when you're sending something, the canceling operation result in a `aborted` error code in timer callback.

**Comment by cewh** [comment]
Ok thanks!
