### ISSUE TITLE
iOS  does not reconnect immediately issue

### ISSUE THREAD

**Issue by tuyuanyou** [socketio/socket.io-client-cpp#210]
socket does not reconnect immediately when there is no network. However, socket will not reconnect until the heartbeats return.So,What should I do if I want to immediately reconnect.

**Comment by leoagle** [comment]
你好,我在ios用socket.io也遇到同样的问题的.请问你是找到解决的办法了吗? @tuyuanyou

**Comment by leoagle** [comment]
@tuyuanyou 
Hi, I have the same issue as you about reconnect of socket.io on ios. 
Did u find solution?
