### ISSUE TITLE
Connecting to HTTPS webserver

### ISSUE THREAD

**Issue by Soarick** [socketio/socket.io-client-cpp#233]
Hi! I would like the connect to a HTTPS webserver that require .pem certificate for the SSL authentication. The .pem certificate contain username and password e.g "username=123;password=pass123"

However, I could not find any examples for the socket.io https connection. Anyone could point me in the correct direction or have a code example of it? Thanks!

**Comment by CrackerHax** [comment]
Did you try using the tls version?

**Comment by Soarick** [comment]
Hi! Yes managed to get it working with the TLS version.

**Comment by zefaridator** [comment]
Hi @Soarick 
How did you managed it ?
Thkx
