### ISSUE TITLE
how to convert .js -> cpp

### ISSUE THREAD

**Issue by chillin2** [socketio/socket.io-client-cpp#238]
hello 
i have a .js for sio client websocket.
i try to convert to client c++.
.js
            function send(event, data) {
                console.log("** [send] "+ event);
                var auth = {
                    app_user_id : "test1",
                    auth_token : "testtest",
                    app_id : "test"
                }
                var packet = {
                    auth: auth,
                    data: data
                }

                socket.emit(event, packet)
            }
how to make these data type and emit in cpp.
plz help me plz plz plz
one more question.
where can i find websocket client example code in cpp

**Comment by chillin2** [comment]
message::ptr Auth = object_message::create();
	Auth->get_map()["app_user_id"] = string_message::create("test1");
	Auth->get_map()["auth_token"] = string_message::create("testtest");
	Auth->get_map()["app_id"] = string_message::create("test");

	message::ptr packet = object_message::create();
	packet->get_map()["auth"] = Auth;
	packet->get_map()["data"] = string_message::create("test");

	current_socket->emit("initialize", packet);

**Comment by agentile1990** [comment]
@chillin2 From what I understand, this library is designed to be a client to a SocketIO server, which is not exclusively a WebSockets server. While SocketIO runs primarily over WebSockets, when ws:// is unavailable, it falls back to HTTP methods, like polling. 

There is an example in the repo. I believe the one that would be most useful for you would be the console version https://github.com/socketio/socket.io-client-cpp/tree/master/examples/Console

**Comment by chillin2** [comment]
@agentile1990 thanks for the reply! 
I am testing on a socketio server. I want to test it using websocket method.
i want to find websocket examples. but i think console example is not websocket method.
h.connect("ws://127.0.0.1/") Will this be the websocket method?

**Comment by agentile1990** [comment]
@chillin2 - "ws://" stands for  Web Socket, similar to "http://". According to the [SocketIO Server API docs](https://socket.io/docs/server-api/#new-Server-httpServer-options) you can specify 'transports' in your 'options' object when you make the call to new Server(); Options for transports are 'polling' and 'websocket'. 

According to the [SocketIO Client API docs](https://socket.io/docs/client-api/#With-websocket-transport-only), by default, the client establishes a polling connection first, then the connection is upgraded to Web Sockets.

I would imagine in your scenario, you would want to limit the available transports of your server to only accept 'websocket' connections. Then you would want to limit your client to only use websocket connections as well. 

With this library (Socket.IO-Client-CPP), it looks like there is a function definition for "connect" which allows you to pass in 'headers.' It also looks like ultimately, that makes a call to the [websocketpp](https://github.com/zaphoyd/websocketpp) library, which I have no experience with. I always felt that the fallback to polling was a feature of Socket.IO, but its entirely possible that websocketpp implements this as well. 

Hope this helps!
