### ISSUE TITLE
debugging the using console with COUT/printf

### ISSUE THREAD

**Issue by snakehaihai** [socketio/socket.io-client-cpp#253]
Hi
Im tying to use the COUT for debug the sequence. But It seems that I cant shows the cout once start the connection
![image](https://user-images.githubusercontent.com/6070995/77296199-3e507f80-6d22-11ea-911b-81e5c4f765f2.png)

by right I should see connected. but I cant sees it. Same goes for all cout after the connection. I tried static mutex lock  and conditional wait. they both not working http://www.cplusplus.com/reference/condition_variable/condition_variable/wait/

Can any 1 share some inside on how to debug ?

**Comment by xinthose** [comment]
I am not sure.  [My code](https://github.com/xinthose/angular_cpp_websocket/blob/e5b5a293b7c889f49b4b122b8943250fc4b98607/back_end/src/websocket.cpp#L42) does not have that problem.  Perhaps it is related to that error?

**Comment by snakehaihai** [comment]
Quick solution. For socket io to work. you need to use nodejs to install a series of supporting library inorder for the cout to be shown properly. I found some prerequesit.txt on some other library. I follow that list and install it and now it can shown.
