### ISSUE TITLE
Use socket io lib

### ISSUE THREAD

**Issue by ForWarZz** [socketio/socket.io-client-cpp#255]
I followed the tutorial for the installer but I absolutely do not see what I need to import into my project to use and create my client. Thank you for your help! :)

**Comment by xinthose** [comment]
You can view my `websocket.cpp` and associated header file in my [test project](https://github.com/xinthose/angular_cpp_websocket/blob/master/back_end/src/websocket.cpp) if it helps you.

**Comment by jmigual** [comment]
Closing as it seems solved.
