### ISSUE TITLE
how use on('event',arguments...) in  cpp?

### ISSUE THREAD

**Issue by forfuns** [socketio/socket.io-client-cpp#26]
hi, this is my problem
my client cpp code like this : 
```
socket->on("test event",sio::socket::event_listener_aux([&socket,&line](std::string const& name,sio::message::ptr const& data ,bool isAck,sio::message::ptr &ack_resp){
    do something...
}));
```

my server js code like this : 
```

socket.emit('test event','1','2','3');


```

so , how can I receive this argument in cpp code ?
or I just change my server code like this : `socket.emit('test event',['1','2','3']);`
and the client make sure data is `flag_array` ??

thanks !

**Comment by melode11** [comment]
1. you can use `sio::socket::event_listener` instead of `sio::socket::event_listener_aux`, you can get `message::list` from the `event` argument.

2. `socket.emit('test event',['1','2','3'])` also work. Surely you'll receive a array message.

**Comment by forfuns** [comment]
I try to use `message::list ` in the code
like this : 
```
socket->on("test event",sio::socket::event_listener_aux([&socket,&line](std::string const& name,sio::message::list const& data ,bool isAck,sio::message::ptr &ack_resp){
    //but when I use data.size() , just 1 , and I sure my socket.io server use like socket.emit('test event','1','2','3');
   // is something wrong?
}));
```

**Comment by melode11** [comment]
you need to use `sio::socket::event_listener(event& event)` to replace `sio::socket::event_listener_aux`.

**Comment by forfuns** [comment]
thanks , is work. :+1:
