### ISSUE TITLE
vcpkg installation

### ISSUE THREAD

**Issue by ForWarZz** [socketio/socket.io-client-cpp#260]
Hello, i am trying to put sioclient with vcpkg but when i finished installing it there is no instruction to import it into my cmake, can you help me?

**Comment by NateShaq** [comment]
My project automatically grabbed the builds from the vcpkg folder. Be sure to run vcpkg integrate cmd to set the enviroment variables for the project's pathing macros. This is really the easiest way to install anything.

**Comment by ForWarZz** [comment]
It’s good ty
