### ISSUE TITLE
Receive message

### ISSUE THREAD

**Issue by ForWarZz** [socketio/socket.io-client-cpp#261]
hello, I recently created a server with nodejs and I sent a message with the emit function, but I cannot retrieve the sent message. My c ++ app tells me that it received an event but I don't know how to retrieve the message. Thank you for your help.

**Comment by harshil1991** [comment]
I am getting issue, Have you resolved same issue?

**Comment by harshil1991** [comment]
I created sample app, which sends and receive message from  server, over here: 
https://github.com/harshil1991/socketio-client.cpp_sample

You can take reference from it.

**Comment by domingguss** [comment]
```c++
void bindEvents()
{
    current_socket->on("action", socket::event_listener_aux([&](string const& name, message::ptr const& data, bool isAck,message::list &ack_resp)
    {
        auto type = data->get_map()["type"];
        if (type->get_flag() == message::flag_string)
        {
            printf("%s\n", type->get_string().c_str());
        }

    }));
}
```

**Comment by ForWarZz** [comment]
Ty
