### ISSUE TITLE
How to emit a JSON object?

### ISSUE THREAD

**Issue by haitaoxin** [socketio/socket.io-client-cpp#27]
Hello,
I noticed that in \test\sio_test.cpp, nlohmann mentioned that JSON will not compile on Windows:
#ifndef _WIN32
#include "json.hpp" //nlohmann::json cannot build in MSVC
#endif

Does it mean that I cann't emit a JSON object from Win32 client? Here is my object
{
    name: 'Joe',
    age: 25,
    car: {
        photo: <Buffer of an image file>,
        year: 2005
    }
}
If I can, could you give a simple example?

Thanks a lot!

**Comment by melode11** [comment]
This macro is just for unit-test.
But actually there's not direct interface receiving `JSON` object because this lib is not going to be depended on any JSON libraries at interface level.
The correct way is to convert your json object/array to `object_message` or `array_message`.

**Comment by haitaoxin** [comment]
melode11, thank you for the answer. However, I still don't know how to send an object_message. The constructor of this class takes empty input, and it only has get_map() method, so "set_map()", so how can I input a set of key:value pair?

I spent some time to debug the code, still could not find a workaround to send a JSON object (instead of a string in quotations). Could you please give an example of how to do that?

**Comment by melode11** [comment]
`get_map` gives the internal `map` reference, you can set any string - message key-value pair into it.
or just 
```
object_map_ptr->get_map() = your_map;
```

**Comment by melode11** [comment]
suppose you got a json:
```
{
   name:'Bob',
   friends:['Tom','Jim']
}
```
you need to concrete a object_message with below structure:
```
object_message:
           |__name(string): bob(string_message)
           |__friends(string):array_message:Tom(string_message), Jim(string_message)
```
Do I explained clearly?

**Comment by haitaoxin** [comment]
Yes, I followed your suggestion and it works. Thanks again!

**Comment by gallgall** [comment]
Please post a clearly example about this. I really really need it. Thanks a lot!

**Comment by zhyq0520** [comment]
@melode11 
Hi, how will it be able to communicate with sock.io(js version) in this way?

**Comment by liwuking** [comment]
@haitaoxin  can you post a clearly example.  I really really need it. Thanks a lot!
