### ISSUE TITLE
Make install error 

### ISSUE THREAD

**Issue by krishnastvSMSC** [socketio/socket.io-client-cpp#272]
Hello Team,

As per the steps, I installed Boost 1.74.0 and assign path to Cmake. But while make install got error.

<img width="1393" alt="Screenshot 2020-11-20 at 3 37 24 PM" src="https://user-images.githubusercontent.com/45424351/99787852-4af1d580-2b46-11eb-9e68-a85dbe6f384a.png">

Any one help me how to resolve this error.

Thank you

**Comment by naiteon** [comment]
Hi brother. I had similar issue in the past.  Boost asio has renamed after version 1.65 the method basic_stream_socket::get_io_service to bacis_stream_socket::get_executor()  and has renamed io_service  to io_context.

So I had to change my library code like this:

#if MY_BOOST_VERSION > 165
        timer = std::unique_ptr<asio::steady_timer>(new asio::steady_timer(socket->**get_executor**()));
#else
        timer = std::unique_ptr<asio::steady_timer>(new asio::steady_timer(socket->**get_io_service**())); 
#endif


#if MY_BOOST_VERSION > 165
    std::shared_ptr<asio::**io_context**> io_service;
#else
    std::shared_ptr<asio::**io_service**> io_service;
#endif

#if MY_BOOST_VERSION > 165
          io_service = std::make_shared<asio::**io_context**>();
#else
          io_service = std::make_shared<asio::**io_service**>();
#endif



Hope it helps you!

**Comment by krishnastvSMSC** [comment]
Hello naiteon,

Thank you for the response..I will check and let you know.

**Comment by krishnastvSMSC** [comment]
Hello Naiteon,

Can you tell the file name and path..

Thank you

**Comment by Chandramouli-P** [comment]
Hello Naiteon,

Good morning and thank you for your reply. We are unable to find where we need to apply your suggestions. Could you please tell the file name along with the path? Thank you.

Best Regards,
Chandramouli.

**Comment by darrachequesne** [comment]
Boost was removed in https://github.com/socketio/socket.io-client-cpp/commit/af68bf3067ab45dc6a53261284e0da9afd21b636.

I think this can now be closed.
