### ISSUE TITLE
Build fails on Ubuntu 18.04.3 LTS

### ISSUE THREAD

**Issue by sresam89** [socketio/socket.io-client-cpp#275]
This build fails on ubuntu 18.04 as well
same error as in [issue](https://github.com/socketio/socket.io-client-cpp/issues/196) #196 

Can be solved by [using this comment](https://github.com/socketio/socket.io-client-cpp/issues/196#issuecomment-376882557)

**Comment by ProductOfAmerica** [comment]
@sresam89 why open this? It was solved. Is that [solution](https://github.com/socketio/socket.io-client-cpp/issues/196#issuecomment-376882557) not working for you?

**Comment by darrachequesne** [comment]
Fixed by https://github.com/socketio/socket.io-client-cpp/commit/af68bf3067ab45dc6a53261284e0da9afd21b636.
