### ISSUE TITLE
Fatal Error: 'websocketpp/client.hpp' File not found

### ISSUE THREAD

**Issue by matt-attalla** [socketio/socket.io-client-cpp#278]
Hi all,

I'm on macOS Catalina (10.15.3) and installed boost version 1.74.0 via homebrew, updated the `lib/websocketpp` submodule with a `git pull origin master` and followed the instructions here: 
https://github.com/socketio/socket.io-client-cpp/blob/master/INSTALL.md#with-cmake

After doing a `cmake` and `make install` everything installed correctly.

I'm not writing my code in an IDE so I'll have to compile and link everything together myself. 

My source code (main.cpp) is:
```
#include "/Users/matt_attalla/Desktop/test-socket.io-cpp/socket.io-client-cpp/build/include/sio_client.h"
#include "/Users/matt_attalla/Desktop/test-socket.io-cpp/socket.io-client-cpp/build/include/sio_message.h"
#include "/Users/matt_attalla/Desktop/test-socket.io-cpp/socket.io-client-cpp/build/include/sio_socket.h"

int main () {
    sio::client io;
    io.connect("http://127.0.0.1:3000");
    return 0;
}
```
 
I'm trying to compile everything with: 
`g++ main.cpp ./src/sio_client.cpp ./src/sio_socket.cpp ./src/internal/sio_client_impl.cpp ./src/internal/sio_packet.cpp -o test`

This is resulting in an error saying: 
```
In file included from ./src/sio_client.cpp:8:
./src/internal/sio_client_impl.h:15:10: fatal error: 'websocketpp/client.hpp' file not found
#include <websocketpp/client.hpp>
         ^~~~~~~~~~~~~~~~~~~~~~~~
12 warnings and 1 error generated.
```

There are two `libsioclient.a` files in both the root directory and the `./build/lib/release/` folder

Am I missing to include either one of those libraries or something? Am I doing something wrong?

I'm trying to connect this to a node.js server and I really want this to work.

Please help!

**Comment by matt-attalla** [comment]
I fixed this problem and if this helps anyone, I did the following: 

```
g++ -std=c++11 main.cpp ./src/sio_client.cpp ./src/internal/sio_client_impl.cpp ./src/internal/sio_packet.cpp ./src/sio_socket.cpp -o main -I ./lib/websocketpp -I ./lib/rapidjson/include
```
Then did:
`./main`

Or you can do it all on one line:
```
g++ -std=c++11 main.cpp ./src/sio_client.cpp ./src/internal/sio_client_impl.cpp ./src/internal/sio_packet.cpp ./src/sio_socket.cpp -o main -I ./lib/websocketpp -I ./lib/rapidjson/include && ./main
```

I had to compile this with C++11 and include all of the .cpp files throughout the `./src` folder and included both the `./libwebsocketpp` and the `./lib/rapidjson/include` folders so it can look for all of the necessary header files. 

This will compile and include all submodules and then run the main executable that's created after compiling everything.

Hope this helps!

**Comment by ProductOfAmerica** [comment]
Close this issue? Not an issue? @matt-attalla
