### ISSUE TITLE
No events over https connection

### ISSUE THREAD

**Issue by bbilas** [socketio/socket.io-client-cpp#279]
Hello, I've experienced the problem with no events from the server when I use a connection over HTTPS. I've verified it with HTTP and everything works quite well there. Is there anyone who faced similar problems?+

**Comment by tobiasfriden** [comment]
Had the same problem, I got it to work by using

```target_link_libraries(my_target sioclient_tls)```

instead of 

```target_link_libraries(my_target sioclient)```

in my `CMakeLists.txt`

**Comment by bbilas** [comment]
I'm closing that due to the fact that was the cloud problem.
