### ISSUE TITLE
Issues in using ASIO standalone

### ISSUE THREAD

**Issue by LuzyCat** [socketio/socket.io-client-cpp#283]
Hello,
I have a problem when adding the socket.io client library to my project.
In 'sio_client_impl.h', I got a C2440 error because `boost::asio::io_sevice is not compatible with asio::io_service &`.
However, if I don't include the boost library, ASIO will also be disabled.
According to #176, there is no dependency on boost and ASIO, but I don't know why the problem occurred.
Is it just my own problem?

Regards,
Meejin Kim

**Comment by Nelson-numerical-software** [comment]
do not forget to add : #define ASIO_STANDALONE  ;) 
see https://github.com/socketio/socket.io-client-cpp/blob/master/CMakeLists.txt#L24
info is missing in https://github.com/socketio/socket.io-client-cpp/blob/master/INSTALL.md#without-cmake

**Comment by LuzyCat** [comment]
Thanks for your help.
It works well:)

Have a good day.
