### ISSUE TITLE
MinGW Cross-Compile on Linux for Windows

### ISSUE THREAD

**Issue by nickwebha** [socketio/socket.io-client-cpp#294]
I am running Ubuntu 20.04.

Is there a way to cross compile for Windows? I do not know much about CMake but I looked in `CMakeLists.txt` and did not see anything. I tried adding `-D CMAKE_CXX_COMPILER=/usr/bin/x86_64-w64-mingw32-g++` to the command but then I just get `"/usr/bin/x86_64-w64-mingw32-gcc" is not able to compile a simple test program`.

**Comment by jmigual** [comment]
Hi, I think this question falls outside the scope of this repository and is more a CMake question. I would suggest looking at this SO answer: https://stackoverflow.com/a/48422547/4005637
