### ISSUE TITLE
sio::socket::impl::on_close() crashed in webrtc

### ISSUE THREAD

**Issue by xp19870106** [socketio/socket.io-client-cpp#295]
Process:               NDMeeting [57251]
Path:                  /Users/USER/Documents/*/xxxx.app/Contents/MacOS/NDMeeting
Identifier:            cn.nd.ndmeetig
Version:               1.2.9
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           NDMeeting [57251]
User ID:               501

Date/Time:             2021-03-05 11:17:53.996 +0800
OS Version:            Mac OS X 10.14.6 (18G84)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        7F0AE481-B1B4-BACE-7E4D-97C69BA9F610

Time Awake Since Boot: 910000 seconds

System Integrity Protection: enabled

Crashed Thread:        22

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type std::__1::system_error: mutex lock failed: Invalid argument
abort() called

Thread 0:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff5adf31d6 __close_nocancel + 10
1   libsystem_c.dylib             	0x00007fff5ad4194c fclose + 92
2   cn.nd.ndmeetig                	0x0000000105584dd6 webrtc::FileWrapper::Close() + 22 (file_wrapper.cc:116)
3   cn.nd.ndmeetig                	0x0000000105559b36 rtc::FileRotatingStream::~FileRotatingStream() + 118 (file_rotating_stream.cc:194)
4   cn.nd.ndmeetig                	0x000000010555aa9e rtc::CallSessionFileRotatingStream::~CallSessionFileRotatingStream() + 14 (file_rotating_stream.h:144)
5   cn.nd.ndmeetig                	0x00000001055844fa rtc::CallSessionFileRotatingLogSink::~CallSessionFileRotatingLogSink() + 42 (log_sinks.cc:74)
6   cn.nd.ndmeetig                	0x0000000105bf99cb -[RTCFileLogger dealloc] + 27 (RTCFileLogger.mm:83)
7   cn.nd.ndmeetig                	0x000000010535f99b -[NdRtcEngine .cxx_destruct] + 123 (ndrtc_engine.mm:45)
8   libobjc.A.dylib               	0x00007fff594eac18 object_cxxDestructFromClass(objc_object*, objc_class*) + 127
9   libobjc.A.dylib               	0x00007fff594e3792 objc_destructInstance + 76
10  libobjc.A.dylib               	0x00007fff594e3735 object_dispose + 19
11  cn.nd.ndmeetig                	0x000000010534729d -[NdRtcEngine dealloc] + 205 (ndrtc_engine.mm:66)
12  cn.nd.ndmeetig                	0x0000000105360e62 NdrtcEngineAdapter::initialize(NDSDK::RtcContext const&) + 34 (ndrtc_sdk-adapter.mm:30)
13  cn.nd.ndmeetig                	0x000000010533e822 MeetingWorkFlowMgr::initRtcHelper() + 98 (meeting_workflow_mgr.cpp:1566)
14  cn.nd.ndmeetig                	0x000000010533de94 MeetingWorkFlowMgr::start(NDSDK::tagMeetingStartParam&) + 68 (meeting_workflow_mgr.cpp:188)
15  cn.nd.ndmeetig                	0x000000010537efae non-virtual thunk to NDSDK::CMeetingServiceImpl::start(NDSDK::tagMeetingStartParam&) + 94
16  cn.nd.ndmeetig                	0x0000000105325291 LoginDialog::p_join(QString, QString, QString) + 545 (login_dialog_mac.mm:348)
17  cn.nd.ndmeetig                	0x0000000105324063 LoginDialog::on_sig_meetingCreated(int, QString) + 163 (login_dialog_mac.mm:252)
18  cn.nd.ndmeetig                	0x0000000105327421 QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<int, QString>, void, void (LoginDialog::*)(int, QString)>::call(void (LoginDialog::*)(int, QString), LoginDialog*, void**) + 65 (qobjectdefs_impl.h:152)
19  org.qt-project.QtCore         	0x0000000107396cff QObject::event(QEvent*) + 943
20  org.qt-project.QtWidgets      	0x00000001062f1a3a QWidget::event(QEvent*) + 4698
21  org.qt-project.QtWidgets      	0x00000001062b5f5a QApplicationPrivate::notify_helper(QObject*, QEvent*) + 266
22  org.qt-project.QtWidgets      	0x00000001062b73e6 QApplication::notify(QObject*, QEvent*) + 598
23  org.qt-project.QtCore         	0x000000010736b9f4 QCoreApplication::notifyInternal2(QObject*, QEvent*) + 212
24  org.qt-project.QtCore         	0x000000010736cbe9 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) + 809
25  libqcocoa.dylib               	0x00000001092d00e9 0x109297000 + 233705
26  libqcocoa.dylib               	0x00000001092d0858 0x109297000 + 235608
27  com.apple.CoreFoundation      	0x00007fff2ed35683 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
28  com.apple.CoreFoundation      	0x00007fff2ed35629 __CFRunLoopDoSource0 + 108
29  com.apple.CoreFoundation      	0x00007fff2ed18feb __CFRunLoopDoSources0 + 195
30  com.apple.CoreFoundation      	0x00007fff2ed185b5 __CFRunLoopRun + 1189
31  com.apple.CoreFoundation      	0x00007fff2ed17ebe CFRunLoopRunSpecific + 455
32  com.apple.HIToolbox           	0x00007fff2df771ab RunCurrentEventLoopInMode + 292
33  com.apple.HIToolbox           	0x00007fff2df76ee5 ReceiveNextEventCommon + 603
34  com.apple.HIToolbox           	0x00007fff2df76c76 _BlockUntilNextEventMatchingListInModeWithFilter + 64
35  com.apple.AppKit              	0x00007fff2c30f79d _DPSNextEvent + 1135
36  com.apple.AppKit              	0x00007fff2c30e48b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
37  com.apple.AppKit              	0x00007fff2c3085a8 -[NSApplication run] + 699
38  libqcocoa.dylib               	0x00000001092cf5d3 0x109297000 + 230867
39  org.qt-project.QtCore         	0x0000000107367a7f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
40  org.qt-project.QtCore         	0x000000010736c002 QCoreApplication::exec() + 130
41  cn.nd.ndmeetig                	0x0000000105327cde main + 206
42  libdyld.dylib                 	0x00007fff5acbd3d5 start + 1

Thread 1:
0   libsystem_pthread.dylib       	0x00007fff5aeb03f0 start_wqthread + 0

Thread 2:
0   libsystem_pthread.dylib       	0x00007fff5aeb03f0 start_wqthread + 0

Thread 3:: com.apple.NSEventThread
0   libsystem_kernel.dylib        	0x00007fff5adf222a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff5adf276c mach_msg + 60
2   com.apple.CoreFoundation      	0x00007fff2ed191ee __CFRunLoopServiceMachPort + 328
3   com.apple.CoreFoundation      	0x00007fff2ed1875c __CFRunLoopRun + 1612
4   com.apple.CoreFoundation      	0x00007fff2ed17ebe CFRunLoopRunSpecific + 455
5   com.apple.AppKit              	0x00007fff2c3174c2 _NSEventThread + 175
6   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 4:: Qt bearer thread
0   libsystem_kernel.dylib        	0x00007fff5adfa36e poll + 10
1   org.qt-project.QtCore         	0x00000001073c353a qt_safe_poll(pollfd*, unsigned int, timespec const*) + 90
2   org.qt-project.QtCore         	0x00000001073c4f31 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 833
3   org.qt-project.QtCore         	0x0000000107367a7f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
4   org.qt-project.QtCore         	0x00000001071978e3 QThread::exec() + 131
5   org.qt-project.QtCore         	0x0000000107198849 0x107176000 + 141385
6   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 5:: QNetworkAccessManager thread
0   libsystem_kernel.dylib        	0x00007fff5adfa36e poll + 10
1   org.qt-project.QtCore         	0x00000001073c353a qt_safe_poll(pollfd*, unsigned int, timespec const*) + 90
2   org.qt-project.QtCore         	0x00000001073c4f31 QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) + 833
3   org.qt-project.QtCore         	0x0000000107367a7f QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 431
4   org.qt-project.QtCore         	0x00000001071978e3 QThread::exec() + 131
5   org.qt-project.QtCore         	0x0000000107198849 0x107176000 + 141385
6   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 6:: Thread (pooled)
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb456e _pthread_cond_wait + 722
2   org.qt-project.QtCore         	0x00000001071a06bf 0x107176000 + 173759
3   org.qt-project.QtCore         	0x00000001071a038e 0x107176000 + 172942
4   org.qt-project.QtCore         	0x00000001071a02ad QWaitCondition::wait(QMutex*, QDeadlineTimer) + 93
5   org.qt-project.QtCore         	0x00000001071a021e QWaitCondition::wait(QMutex*, unsigned long) + 62
6   org.qt-project.QtCore         	0x000000010719ce44 0x107176000 + 159300
7   org.qt-project.QtCore         	0x0000000107198849 0x107176000 + 141385
8   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
9   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
10  libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 7:
0   libsystem_pthread.dylib       	0x00007fff5aeb03f0 start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib       	0x00007fff5aeb03f0 start_wqthread + 0

Thread 9:
0   libsystem_kernel.dylib        	0x00007fff5adf227e semaphore_timedwait_trap + 10
1   libdispatch.dylib             	0x00007fff5ac70c99 _dispatch_sema4_timedwait + 76
2   libdispatch.dylib             	0x00007fff5ac71377 _dispatch_semaphore_wait_slow + 58
3   libdispatch.dylib             	0x00007fff5ac7e1fd _dispatch_worker_thread + 317
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 10:: com.apple.CFSocket.private
0   libsystem_kernel.dylib        	0x00007fff5adf961a __select + 10
1   com.apple.CoreFoundation      	0x00007fff2ed46b72 __CFSocketManager + 635
2   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
3   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
4   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 11:
0   libsystem_kernel.dylib        	0x00007fff5adf5f32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5ad81914 nanosleep + 199
2   libc++.1.dylib                	0x00007fff57ef2dc4 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3   cn.nd.ndmeetig                	0x00000001054b26a1 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, owt::conference::ConferenceSocketSignalingChannel::OnReconnectionTicket(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_30> >(void*) + 65 (thread:283)
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 12:: peerconnection_dependency_factory_thread
0   libsystem_kernel.dylib        	0x00007fff5adf878e kevent + 10
1   cn.nd.ndmeetig                	0x00000001055778db rtc::PhysicalSocketServer::kq_dispatch(int, int, bool) + 283 (physical_socket_server.cc:2166)
2   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
3   cn.nd.ndmeetig                	0x00000001055829a3 rtc::Thread::ProcessMessages(int) + 115 (thread.cc:526)
4   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
5   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 13:: worker_thread
0   libsystem_kernel.dylib        	0x00007fff5adf878e kevent + 10
1   cn.nd.ndmeetig                	0x00000001055778db rtc::PhysicalSocketServer::kq_dispatch(int, int, bool) + 283 (physical_socket_server.cc:2166)
2   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
3   cn.nd.ndmeetig                	0x0000000105582a0e rtc::Thread::ProcessMessages(int) + 222 (thread.cc:526)
4   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
5   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 14:: signaling_thread
0   libsystem_kernel.dylib        	0x00007fff5adf878e kevent + 10
1   cn.nd.ndmeetig                	0x00000001055778db rtc::PhysicalSocketServer::kq_dispatch(int, int, bool) + 283 (physical_socket_server.cc:2166)
2   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
3   cn.nd.ndmeetig                	0x0000000105582a0e rtc::Thread::ProcessMessages(int) + 222 (thread.cc:526)
4   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
5   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 15:: network_thread
0   libsystem_kernel.dylib        	0x00007fff5adf878e kevent + 10
1   cn.nd.ndmeetig                	0x00000001055778db rtc::PhysicalSocketServer::kq_dispatch(int, int, bool) + 283 (physical_socket_server.cc:2166)
2   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
3   cn.nd.ndmeetig                	0x0000000105582a0e rtc::Thread::ProcessMessages(int) + 222 (thread.cc:526)
4   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
5   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 16:: network_thread 0x0x7fb756c7dab0
0   libsystem_kernel.dylib        	0x00007fff5adf878e kevent + 10
1   cn.nd.ndmeetig                	0x00000001055778db rtc::PhysicalSocketServer::kq_dispatch(int, int, bool) + 283 (physical_socket_server.cc:2166)
2   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
3   cn.nd.ndmeetig                	0x00000001055829a3 rtc::Thread::ProcessMessages(int) + 115 (thread.cc:526)
4   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
5   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
6   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
7   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 17:: worker_thread 0x0x7fb756c7dc10
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb456e _pthread_cond_wait + 722
2   cn.nd.ndmeetig                	0x0000000105552605 rtc::Event::Wait(int, int) + 549 (event.cc:181)
3   cn.nd.ndmeetig                	0x000000010556bf32 rtc::NullSocketServer::Wait(int, bool) + 18 (null_socket_server.cc:25)
4   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
5   cn.nd.ndmeetig                	0x0000000105582a0e rtc::Thread::ProcessMessages(int) + 222 (thread.cc:526)
6   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
7   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 18:: signaling_thread 0x0x7fb756c7c950
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb456e _pthread_cond_wait + 722
2   cn.nd.ndmeetig                	0x0000000105552605 rtc::Event::Wait(int, int) + 549 (event.cc:181)
3   cn.nd.ndmeetig                	0x000000010556bf32 rtc::NullSocketServer::Wait(int, bool) + 18 (null_socket_server.cc:25)
4   cn.nd.ndmeetig                	0x0000000105562b3c rtc::MessageQueue::Get(rtc::Message*, int, bool) + 1292 (message_queue.cc:330)
5   cn.nd.ndmeetig                	0x0000000105582a0e rtc::Thread::ProcessMessages(int) + 222 (thread.cc:526)
6   cn.nd.ndmeetig                	0x0000000105582698 rtc::Thread::PreRun(void*) + 88 (thread.cc:68)
7   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
8   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
9   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 19:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb45a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff30a85797 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff30a84d46 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 20:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb45a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff30a85797 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff30a84d46 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 21:
0   libsystem_pthread.dylib       	0x00007fff5aeb03f0 start_wqthread + 0

Thread 22 Crashed:
0   libsystem_kernel.dylib        	0x00007fff5adf82c6 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb3bf1 pthread_kill + 284
2   libsystem_c.dylib             	0x00007fff5ad626a6 abort + 127
3   libc++abi.dylib               	0x00007fff57f3e641 abort_message + 231
4   libc++abi.dylib               	0x00007fff57f3e7c7 default_terminate_handler() + 243
5   libobjc.A.dylib               	0x00007fff594f1eeb _objc_terminate() + 105
6   libc++abi.dylib               	0x00007fff57f4a19e std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff57f49f86 __cxxabiv1::failed_throw(__cxxabiv1::__cxa_exception*) + 27
8   libc++abi.dylib               	0x00007fff57f3cf99 __cxa_throw + 113
9   libc++.1.dylib                	0x00007fff57f300e7 std::__1::__throw_system_error(int, char const*) + 77
10  libc++.1.dylib                	0x00007fff57eea96d std::__1::mutex::lock() + 29
11  cn.nd.ndmeetig                	0x0000000105e3b60c sio::socket::impl::on_close() + 108
12  cn.nd.ndmeetig                	0x0000000105e46b0b boost::asio::detail::wait_handler<std::__1::__bind<void (sio::socket::impl::*)(), sio::socket::impl*>, boost::asio::detail::io_object_executor<boost::asio::executor> >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) + 219
13  cn.nd.ndmeetig                	0x0000000105e437b6 boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) + 806
14  cn.nd.ndmeetig                	0x0000000105e431a2 boost::asio::detail::scheduler::run(boost::system::error_code&) + 258
15  cn.nd.ndmeetig                	0x0000000105e4b3a7 sio::client_impl::run_loop() + 71
16  cn.nd.ndmeetig                	0x0000000105e53e3e void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, std::__1::__bind<void (sio::client_impl::*)(), sio::client_impl*> > >(void*) + 62
17  libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
18  libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
19  libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 23:
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb456e _pthread_cond_wait + 722
2   cn.nd.ndmeetig                	0x0000000105e4366b boost::asio::detail::scheduler::do_run_one(boost::asio::detail::conditionally_enabled_mutex::scoped_lock&, boost::asio::detail::scheduler_thread_info&, boost::system::error_code const&) + 475
3   cn.nd.ndmeetig                	0x0000000105e431a2 boost::asio::detail::scheduler::run(boost::system::error_code&) + 258
4   cn.nd.ndmeetig                	0x0000000105e4304c boost::asio::detail::posix_thread::func<boost::asio::detail::resolver_service_base::work_scheduler_runner>::run() + 60
5   cn.nd.ndmeetig                	0x0000000105e42fe0 boost_asio_detail_posix_thread_function + 16
6   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 24:
0   libsystem_kernel.dylib        	0x00007fff5adf5f32 __semwait_signal + 10
1   libsystem_c.dylib             	0x00007fff5ad81914 nanosleep + 199
2   libc++.1.dylib                	0x00007fff57ef2dc4 std::__1::this_thread::sleep_for(std::__1::chrono::duration<long long, std::__1::ratio<1l, 1000000000l> > const&) + 73
3   cn.nd.ndmeetig                	0x00000001054b26a1 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, owt::conference::ConferenceSocketSignalingChannel::OnReconnectionTicket(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)::$_30> >(void*) + 65 (thread:283)
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 25:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb45a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff30a85797 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff30a84d46 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 26:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb45a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff30a85797 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff30a84d46 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 27:: CVDisplayLink
0   libsystem_kernel.dylib        	0x00007fff5adf586a __psynch_cvwait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb45a1 _pthread_cond_wait + 773
2   com.apple.CoreVideo           	0x00007fff30a85797 CVDisplayLink::waitUntil(unsigned long long) + 229
3   com.apple.CoreVideo           	0x00007fff30a84d46 CVDisplayLink::runIOThread() + 482
4   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
5   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
6   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 28:
0   libsystem_kernel.dylib        	0x00007fff5adf49de __ulock_wait + 10
1   libsystem_pthread.dylib       	0x00007fff5aeb56de _pthread_join + 358
2   libc++.1.dylib                	0x00007fff57f30148 std::__1::thread::join() + 24
3   cn.nd.ndmeetig                	0x0000000105e49fe5 sio::client_impl::~client_impl() + 133
4   cn.nd.ndmeetig                	0x0000000105e36cf6 sio::client::~client() + 22
5   cn.nd.ndmeetig                	0x00000001054a5f97 void* std::__1::__thread_proxy<std::__1::tuple<std::__1::unique_ptr<std::__1::__thread_struct, std::__1::default_delete<std::__1::__thread_struct> >, owt::conference::ConferenceSocketSignalingChannel::~ConferenceSocketSignalingChannel()::$_0> >(void*) + 167 (thread:283)
6   libsystem_pthread.dylib       	0x00007fff5aeb12eb _pthread_body + 126
7   libsystem_pthread.dylib       	0x00007fff5aeb4249 _pthread_start + 66
8   libsystem_pthread.dylib       	0x00007fff5aeb040d thread_start + 13

Thread 22 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007000076ab000  rcx: 0x00007000076aa5e8  rdx: 0x0000000000000000
  rdi: 0x000000000001ec73  rsi: 0x0000000000000006  rbp: 0x00007000076aa620  rsp: 0x00007000076aa5e8
   r8: 0x00007000076aa4b0   r9: 0x00007000076aa680  r10: 0x0000000000000000  r11: 0x0000000000000206
  r12: 0x000000000001ec73  r13: 0x0000003000000008  r14: 0x0000000000000006  r15: 0x000000000000002d
  rip: 0x00007fff5adf82c6  rfl: 0x0000000000000206  cr2: 0x00007fff9150a188

**Comment by ziweiyang20** [comment]
Hi, are you using owt server? v5.0?

**Comment by xp19870106** [comment]
I've solved it
