### ISSUE TITLE
socket.io v4 support ?

### ISSUE THREAD

**Issue by Nelson-numerical-software** [socketio/socket.io-client-cpp#298]
https://github.com/socketio/socket.io/releases/tag/4.0.0
Does it work with socket.io-client-cpp ?

**Comment by darrachequesne** [comment]
Hi! Yes, the v4 only contains a few breaking changes at the API level on the server-side, so the current C++ client is compatible. The [compatibility table](https://github.com/socketio/socket.io-client-cpp#compatibility-table) was updated.

Reference: https://socket.io/docs/v4/migrating-from-3-x-to-4-0/

**Comment by Nelson-numerical-software** [comment]
I confirm :) Thanks for your work and your support
