### ISSUE TITLE
how to get binary data?

### ISSUE THREAD

**Issue by hyok** [socketio/socket.io-client-cpp#3]
our server create a buffer from node.js
and we wanna send to client this(actually we want to send image data)
how to receive buffer data in client?
i used get_binary() but application shut down

### Nodejs
```javascript

var Buffer = require('buffer').Buffer;
var buf = new Buffer(4);
buf.writeInt32BE(1, 0);
console.log(buf);

socket.emit('stream', {stream : buf } );
```

### C++
```c++
h.bind_event("stream", [&](string const& name, message::ptr const& data, bool isAck,message::ptr &ack_resp){//message
	_lock.lock();
       data->get_map()["stream"]->get_binary();
       _lock.unlock();
});

```

**Comment by melode11** [comment]
can you test the message::ptr->get_flag() first to see what type it is.

**Comment by hyok** [comment]
it goes array in accept_message() (sio_packet.cpp)....when i chage flag binary to flag_array so in  accept_binary_message(), application shut down ,it meeting write_buffer->reserve(msg.get_binary()->size()+1)..........and i tried to chage msg.get_binary()->size()+1 to 100*sizeof(char) application shut down at write_buffer->append(*(msg.get_binary()));

**Comment by hyok** [comment]
i found some codes, and there is no function checking if value is binary from_json function at sio_packet.cpp
does it make problem?

**Comment by melode11** [comment]
Thanks for reporting this, I've found a bug of sio_packet.cpp which will ignore the first received binary.
Fix is here:
https://github.com/socketio/socket.io-client-cpp/commit/d7f5ceb8595209c9c2aa438756cfa5d2f4528aaa
