### ISSUE TITLE
a cmake compiler flag problem

### ISSUE THREAD

**Issue by douxing** [socketio/socket.io-client-cpp#31]
i am making a .so file out of libsioclient.a, and /usr/bin/ld says relocation error, require me to recompile with -fPIC, so i use this command to cmake again:
``` 
cmake -DBOOST_ROOT=path_to_boost -DBOOST_VER=my_boost_version -DCMAKE_CXX_FLAGS=-fPIC ./
```
and in ./CMakeFiles/sioclient_tls.dir/flags.make:5 and ./CMakeFiles/sioclient_tls.dir/flags.make:5: -fPIC was added to CXX_FLAGS and my dynamic library was generated

however, this problem still exists in the libboost_*.a files, and i have to use my own boost libraries.
any idea to fix this?

ps. my platform is ubuntu 1404LTS, and using [repo at this commit](https://github.com/socketio/socket.io-client-cpp/tree/71f49fabf7e827d1d1e8899f9c80578f52c5cd48) (Jun.15th)

**Comment by melode11** [comment]
Likely you're linking your .so on x64 platform which PIC is a must. To make a PIC shared lib, you need make every input whatever static or dynamic to be PIC. So seems you need to remake your boost lib with -fPIC.

**Comment by douxing** [comment]
@melode11  thanks for the reply.
you are right, i have rebuild the boost with cxxflags='-fPIC' and g++ does not complain anymore when linking.
