### ISSUE TITLE
Cannot build without boost

### ISSUE THREAD

**Issue by eitanpinchover** [socketio/socket.io-client-cpp#313]
After following the steps of the installation instructions, and trying to build, I'm receiving the following compilation error:
`Cannot open include file: 'boost/bind.hpp': No such file or directory`, 
I noticed that boost has recently removed from this project dependencies, so is it possible it is not entirely removed?

**Comment by jmigual** [comment]
Hi, if you are using CMake you should be able to build it without boost. If you are trying to build it without CMake we've updated the build instructions as you need to add some extra definitions. Can you check if the issue is still there?

**Comment by qljsky** [comment]
#include <cstdint>
#ifdef _WIN32

```
 #define ASIO_STANDALONE
 #define _WEBSOCKETPP_CPP11_STL_
```

#define INTIALIZER(__TYPE__)
#else
#define _WEBSOCKETPP_CPP11_STL_ 1
#define INTIALIZER(__TYPE__) (__TYPE__)
#endif
#include <websocketpp/client.hpp>
#if _DEBUG
#if SIO_TLS
#include <websocketpp/config/debug_asio.hpp>
typedef websocketpp::config::debug_asio_tls client_config;
#else
#include <websocketpp/config/debug_asio_no_tls.hpp>
typedef websocketpp::config::debug_asio client_config;
#endif //SIO_TLS
