### ISSUE TITLE
iOS example not working

### ISSUE THREAD

**Issue by juan-arias** [socketio/socket.io-client-cpp#32]
I've followed all the steps specified in this page https://github.com/socketio/socket.io-client-cpp/blob/master/examples/iOS/README.md

This is the output after running `bash ./boost.sh` https://www.dropbox.com/s/ccs2803tegro0t6/socket.io-client-cpp_iOS_ErrorLog.txt?dl=0
The specific error part is: 

```
Framework: Building /Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/osx/framework/boost.framework from /Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/osx/build...
Framework: Setting up directories...
Framework: Creating symlinks...
Lipoing library into /Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/osx/framework/boost.framework/Versions/A/boost...
fatal error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: empty archive with no architecture specification: /Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/osx/build/i386/libboost.a (can't determine architecture for it)

Aborted: Lipo /Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/osx/framework failed
```

Do I have to install anything else to make this work?
I'm on a MacBook Pro with a recently installed OSX Yosemite (10.10.3) and xCode v6.3.2

Or is there any other way to get the libsioclient.a sio_client.h and sio_message.h files?

PD: I've tried to get help from https://socketio.slack.com/ but nobody would help

Thanks

**Comment by melode11** [comment]
Seems you're using a OSX framework for iOS target?

**Comment by iglooJuan** [comment]
Hi,
I'm just following all the instructions on this page https://github.com/socketio/socket.io-client-cpp/blob/master/examples/iOS/README.md

Is there a setting I have to change somewhere? Or the script in that page are incorrect? Or do I have to install boost from another repository and then use it here?

**Comment by LittleLittle** [comment]
The script works for me.

/Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/**osx**/build/i386/libboost.a should be /Users/juan/Documents/sio/socket.io-client-cpp/examples/iOS/SioChatDemo/boost/**ios**/build/i386/libboost.a

**Comment by iglooJuan** [comment]
I commented line 372 and now it completes without errors:

`#buildFramework $OSXFRAMEWORKDIR $OSXBUILDDIR`

**Comment by LoganathanB** [comment]
Thanks @iglooJuan .
