### ISSUE TITLE
can not take custom path

### ISSUE THREAD

**Issue by pkgvrpdm** [socketio/socket.io-client-cpp#337]
I am not able to use custom path as the path in following code doesn't work

 string url = "https://dev.symxyz.com";

  std::map<std::string, std::string> query;
  query["path"]   = "/interactive/socket.io";
  query["token"]  = authorization_token;

_io->connect(url, query);

path in the connection remains the same   "/socket.io"

It should have changed to  "/interactive/socket.io"

This is old bug and still remains.

**Comment by darrachequesne** [comment]
You can add the path in the url directly:

```cpp
string url = "https://dev.symxyz.com/interactive/socket.io";

std::map<std::string, std::string> query;
query["token"] = authorization_token;
```

Related: https://github.com/socketio/socket.io-client-cpp/commit/36a8cd45272aa51f0f6ef27aa4744dbc6e8421f7

**Comment by pkgvrpdm** [comment]
I tried, but it doesn't work in version 2.x.
I had to hardcode my part inside file "sio_client_impl.cpp".
