### ISSUE TITLE
JNI support !!!

### ISSUE THREAD

**Issue by L3DEVIL** [socketio/socket.io-client-cpp#341]
I am no idea how to use socket.io in JNI at first I use socket.io java but the modder's easily cracked it so I try to convert it to a shared library anyone pls help give some hints about implementation how to install socket.io on JNI and connect to server

**Comment by L3DEVIL** [comment]
Pls

**Comment by darrachequesne** [comment]
> the modder's easily cracked it

Could you please explain the issue? Is there something that we should fix in the java client?

**Comment by L3DEVIL** [comment]
> > the modder's easily cracked it
> 
> Could you please explain the issue? Is there something that we should fix in the java client?

Yes they use to reverse-engineering the smali to java and modify the socket.io part

**Comment by jmigual** [comment]
For the Java version of the client please go to: https://github.com/socketio/socket.io-client-java
