### ISSUE TITLE
How to use echo server in source code?

### ISSUE THREAD

**Issue by linuxrd007** [socketio/socket.io-client-cpp#354]
Hi,

Reference figure as follows.
Is there use "cmake ./" and than "make insstall" can be install echo server to raspberry pi?
If it does, how to remove it after test?

Thank you

![NB_Image_20220316_133755](https://user-images.githubusercontent.com/18640144/158523743-a84c8052-3138-4214-b68a-ca755613b911.png)
.

**Comment by linuxrd007** [comment]
Hi,
I try "cmake" & "make" build this test project, it generates an executable "sio_test". There is just show "All tests passed" after execute, not the test echo server!?
How to buile/use a echo server in example?

Thank you.

**Comment by jmigual** [comment]
Hi, this is not an example. This is the code to generate the test cases. To see an example please go to the examples folder: https://github.com/socketio/socket.io-client-cpp/tree/master/examples/

**Comment by linuxrd007** [comment]
Hi,
There was client source code in example, I want try this client function so I need a test server.
I see echo server in test folder, thus that is test server can be test client, I think.
Build example client code is ok, how to test it?

Thank you.

**Comment by jmigual** [comment]
For the test server you need to use the javascript library [socketio/socket.io](https://github.com/socketio/socket.io) and create a server there. This library is client only and cannot be used as a server
