### ISSUE TITLE
conflict of key word 'emit' with qt

### ISSUE THREAD

**Issue by h20282** [socketio/socket.io-client-cpp#357]
in qt, emit is a key word. [qt signals and slots](https://doc.qt.io/qt-5/signalsandslots.html)
so the function sio::socket::emit() conflict.
maybe we should change it? such as 'sio_emit'

**Comment by jmigual** [comment]
Hi, as this is an issue created by Qt, the suggested approach is to add the `QT_NO_KEYWORDS` macro definition that changes `emit` to `QT_EMIT`. Check the Qt examples folder for more information.
