### ISSUE TITLE
Android?

### ISSUE THREAD

**Issue by cal117** [socketio/socket.io-client-cpp#358]
Is there any way to build this for android? I am trying to use this for a C++ project that runs on an android device, it does not use JNI/Java

**Comment by jmigual** [comment]
Hi, have you tried the instructions to build the library [without cmake](https://github.com/socketio/socket.io-client-cpp/blob/master/INSTALL.md#without-cmake)?

**Comment by cal117** [comment]
I got this library to work on Android by copying the source files

**Comment by cal117** [comment]
I don't see why android isn't supported in the build instructions
