### ISSUE TITLE
F this error

### ISSUE THREAD

**Issue by pavel1337228** [socketio/socket.io-client-cpp#359]
g++ -LC:\Users\Kosmolet\vcpkg\installed\x64-windows-static\debug\lib -lsioclient -shared -o shared_lib.dll shared_lib.o -Wl,--out-implib,libshared_lib.a
shared_lib.o:shared_lib.cpp:(.text+0x31): undefined reference to `sio::client::~client()'
shared_lib.o:shared_lib.cpp:(.text+0x68): undefined reference to `sio::client::client()'
collect2.exe: error: ld returned 1 exit status

**Comment by jmigual** [comment]
Hi, it seems that the socket io shared DLL is not being found by the compiler

**Comment by jmigual** [comment]
Have you tried following the instructions to [compile without CMake](https://github.com/socketio/socket.io-client-cpp/blob/master/INSTALL.md#without-cmake)?

**Comment by edde746** [comment]
Adding this to my CMakeLists.txt solved it for me;
```
find_library(SIOCLIENT_LIBRARY sioclient)
target_include_directories(foo PRIVATE ${sioclient})
target_link_libraries(foo PRIVATE ${SIOCLIENT_LIBRARY})
``` [(from here)](https://vcpkg.io/en/docs/examples/installing-and-using-packages.html#handling-libraries-without-native-cmake-support)
