### ISSUE TITLE
Hefty size

### ISSUE THREAD

**Issue by hfossli** [socketio/socket.io-client-cpp#40]
As mentioned here https://github.com/socketio/socket.io-client-cpp/issues/38 building a static library of this framework for iOS is about 60 MB when optimized. That's just too much ! 

The [swift library](https://github.com/socketio/socket.io-client-swift) in comparison:
- has no dependency to other frameworks
- consists of just 13 files (~ 100 KB)

This makes this framework quite less attractive than the swift library. 

I chose this library over swift because of [compatibility issues](https://github.com/CocoaPods/CocoaPods/issues/3807).

**Comment by melode11** [comment]
Static lib is usually much more fat than it actually takes in final app. Would you build your app to see how much the application size growth?

**Comment by hfossli** [comment]
That's a very valid point! My app clocks in on just about 6 MB which is highly acceptable!
