### ISSUE TITLE
support bool in message

### ISSUE THREAD

**Issue by stefanhong** [socketio/socket.io-client-cpp#43]
Currently if json object contains boolean values, the values will be dropped. Boolean values should be supported.

**Comment by LittleLittle** [comment]
+1 for this requirement

**Comment by melode11** [comment]
Feature added.
bbbc1e32dd664c5b0d95074339b997d9b4eb65cf

**Comment by rdesoky** [comment]
You also need to support <null> values. Currently if JSON object contains null, it crashes
