### ISSUE TITLE
support logging configuration

### ISSUE THREAD

**Issue by mingc00** [socketio/socket.io-client-cpp#45]
Currently websocketpp shows some logging messages but there is no method to turn off or configure the log. Logging configuration should be supported.

**Comment by oh3netid** [comment]
+1 for this modification. There are so many logging messages, I am unable to see my own debug output.

**Comment by melode11** [comment]
I had some busy days recently. Request is accepted, but can not guarantee how long I can finish it.

**Comment by melode11** [comment]
I had some busy days recently. Request is accepted, but can not guarantee how long I can finish it.

**Comment by melode11** [comment]
I had some busy days recently. Request is accepted, but can not guarantee how long I can finish it.

**Comment by melode11** [comment]
I had some busy days recently. Request is accepted, but can not guarantee how long I can finish it.

**Comment by KVohra95** [comment]
Does anyone know if this has been implemented?

**Comment by darrachequesne** [comment]
Closed by https://github.com/socketio/socket.io-client-cpp/commit/1b42ce738f4c3e260f79bcb143bfe6efcdce5709.
