### ISSUE TITLE
how compile TLS mode ?

### ISSUE THREAD

**Issue by forfuns** [socketio/socket.io-client-cpp#46]
I don't know what you mean TRGET sioclient_tls  #13 

I try to use libsioclient_tls.a replace libsioclient,but don't work , can't compile.

can you write the code please. 
thanks .

**Comment by LittleLittle** [comment]
I have successfully built a TLS enabled lib for iOS by defining SIO_TLS.

**Comment by forfuns** [comment]
@LittleLittle can u show the  code pls.

**Comment by forfuns** [comment]
I change my code , add #defined SIO_TLS in header file
like this :
```
...
#define SIO_TLS
...
```

but not work , is that right ？
---> Use cmake target sioclient_tls or compile by yourself with SIO_TLS macro.
@melode11

**Comment by AAbhishek1234** [comment]
@forfuns did you get it to working?
