### ISSUE TITLE
error C2664 prevents build in Visual Studio 2013

### ISSUE THREAD

**Issue by RayGui** [socketio/socket.io-client-cpp#47]
Used CMake-gui to create Visual Studio 2013 project. Build solution fails with the error below for both sioclient and sioclient_tls.
Error   9   error C2664: 'boost::asio::basic_waitable_timerstd::chrono::steady_clock,boost::asio::wait_traits<Clock,boost::asio::waitable_timer_service<Clock,WaitTraits>>::basic_waitable_timer(const boost::asio::basic_waitable_timer<Clock,WaitTraits,boost::asio::waitable_timer_service<Clock,WaitTraits>> &)' : cannot convert argument 2 from 'boost::chrono::milliseconds' to 'const std::chrono::time_pointstd::chrono::system_clock,std::chrono::system_clock::duration &'   C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\include\memory   932 1   sioclient_tls
This error is similar to one I found related to websocketpp but the solution offered there does not work. Thanks for your help.

**Comment by jmigual** [comment]
Hi, I'm closing this issue as we don't require Boost anymore
