### ISSUE TITLE
namespaced connection to a server does not work

### ISSUE THREAD

**Issue by nylki** [socketio/socket.io-client-cpp#55]
I am new to webSockets and socket.io, but I understand that I can
create eg. two different namespaces on the server (implemented in nodejs environment) and listen to one of them with:

``` .js
var a = io.of('/a')
var b = io.of('/b')
// […] omitted lines

b.on('connection', handleConnection)
```

I could then connect to the _b_ namespace via a client (in a nodejs environment with socket.io-client) with:

``` .js
var socket = require('socket.io-client')('http://localhost:3000/b')
```

Trying the same in socket.io-client-cpp with

``` .cpp
h.connect("http://127.0.0.1:3000/b");
```

Doesn't seem to work. When I change the server code to not use namespaces like: `io.on('connection', handleConnection)` the connection is established. So I am probably doing something wrong in regards to namespaces? Or is it a bug? thanks!

**Comment by macq-vraman** [comment]
Hello,

As far as I understand it, in socket.io-client-cpp, you can connect with different namespaces. Your client has one socket by namespace.

You bind your events or emit messages with your socket and you call it like this : h.socket(nsp)

And then, in your code

h.connect("http://127.0.0.1:3000");
h.socket(nsp)->on(...);
h.socket(nsp)->emit(...);

**Comment by melode11** [comment]
@macq-vraman is right, and you can get a `socket::ptr` by `h.socket(nsp)` which stand for a specified namespace.
