### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [socketio/socket.io-client-cpp#6]
I would like to point out that identifiers like "[`__SIO_CLIENT__H__`](https://github.com/socketio/socket.io-client-cpp/blob/534262658c0791771cc14ec72797d68fad6b05fa/src/sio_client.h#L7)" and "[`__SIO_MESSAGE_H__`](https://github.com/socketio/socket.io-client-cpp/blob/affd2eee4ac6e208850811458f148b61b7eb09d0/src/sio_message.h#L7)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by melode11** [comment]
@elfring what is your suggestion?

**Comment by elfring** [comment]
How do you think about to read corresponding information sources that describe [the consequences of underscores in such identifiers](http://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?")?

**Comment by melode11** [comment]
Thanks for your suggestion, I'll consider to have a patch for coding style improvement.
There are quite a lot of double underscore prefixed function names around the code, may breaks the rule.
For this case, `__SIO_CLIENT_H__` are macros automatically generated by `QT creator`.

**Comment by melode11** [comment]
f245a8122efada7a7841eddd29d42684cc9f2308  fix those code style issues.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/socketio/socket.io-client-cpp/commit/29e82a64cb9a88e2d4f52990455c2fb89ec1624d#diff-d2d0f173d3d786b539d9fd523a48c90bL121 "Deletion of underscores").
