### ISSUE TITLE
Support null in values

### ISSUE THREAD

**Issue by rdesoky** [socketio/socket.io-client-cpp#61]
If JSON object contains null value, it crashes

**Comment by melode11** [comment]
Oops...What a huge defect, I will fix ASAP.

**Comment by macq-vraman** [comment]
I have the same problem with my project. If you want, I have some free time to share. I think that you should allow nullptr as a valid value for message::ptr everywhere. 

That would lead to problems with default value for message::list in some methods which use constructor with nullptr though. But you could use a static "empty" const message::list variable for these cases.

**Comment by melode11** [comment]
Hi,@macq-vraman I have added a new type called `null_message` , should works.
Your solution seems work too and will save a little more memory, but more changes need to made. I think that won't be a good deal.

**Comment by macq-vraman** [comment]
Ok. Its is indeed easier and working great :)
