### ISSUE TITLE
emit three values

### ISSUE THREAD

**Issue by k1vrA** [socketio/socket.io-client-cpp#7]
Hello dudes!
How i can emit my data in this fomat
emit("event",string,string);

code on node.js:
```socket.on('event', function(data1,data2){....});```

help me pls ._.

**Comment by melode11** [comment]
Array_message
         ---string_message1
         ---string_message2

**Comment by melode11** [comment]
C++ is not as dynamic as js. So you need use message class to compose string array like above. Then use the emit overload for message::ptr

**Comment by melode11** [comment]
I found at this point we can not fullfill that style of variable argument list you posted.
Can you use array_message instead, and receive that array as the 1st argument in your message callback.
But I'm going to support the variable argument overload these days.

**Comment by k1vrA** [comment]
Thx man, i just make new emit method :dancer: But ur solution works too ^_^

**Comment by melode11** [comment]
I've added variable arguments support in latest release.
bc3d745c183d525d9f8d33413112697e5342bb46

**Comment by melode11** [comment]
```C++
message::list li(arg1);
li.push(arg2);
socket.emit("event",li);
```

**Comment by k1vrA** [comment]
thx man ^_^

**Comment by k1vrA** [comment]
@melode11 i have one stupid question, all work in ur test project,but after import all in my main project,i have some errors with boost lib, and others can u make FAQ or just answer how import this lib in iOS project ._. It's rly help for me.

**Comment by k1vrA** [comment]
```
Undefined symbols for architecture x86_64:
  "boost::system::system_category()", referenced from:
      ___cxx_global_var_init6 in sio_client_impl.o
      boost::asio::error::get_system_category() in sio_client_impl.o
      boost::system::error_code::error_code() in sio_client_impl.o
      ___cxx_global_var_init6 in sio_client.o
      boost::asio::error::get_system_category() in sio_client.o
      ___cxx_global_var_init6 in sio_socket.o
      boost::asio::error::get_system_category() in sio_socket.o
      ...
  "boost::system::generic_category()", referenced from:
      ___cxx_global_var_init4 in sio_client_impl.o
      ___cxx_global_var_init5 in sio_client_impl.o
      ___cxx_global_var_init4 in sio_client.o
      ___cxx_global_var_init5 in sio_client.o
      ___cxx_global_var_init4 in sio_socket.o
      ___cxx_global_var_init5 in sio_socket.o
ld: symbol(s) not found for architecture x86_64
```

i have this warning now ._.
Following StackOverFlow, I add -lboost_system in my Xcode project, but it's don't works for me.

**Comment by melode11** [comment]
did you build the boost and have the libboost_system.a

**Comment by melode11** [comment]
You can follow my boost build instructions to got the static lib

**Comment by k1vrA** [comment]
@melode11 with static framework i have "EXC_BAD_ACCESS" in this method
```
void client::connect(const std::string& uri)
    {
        m_impl->connect(uri);
    }
```

**Comment by melode11** [comment]
Weird.
What's your detailed info?

**Comment by oh3netid** [comment]
Hello, thanks for the list example. How would I create an object message?
for example: { title: "my book", characters: ["sam", "bill", "tex"] }

**Comment by melode11** [comment]
message::ptr m =object_message::create();
m->get_map()//put any child messages

**Comment by panhuachao** [comment]
@melode11 Can you write an example for puting any child messages?

**Comment by panhuachao** [comment]
` message::ptr object_map_ptr=object_message::create();
    std::map<std::string,message::ptr> maps=object_map_ptr->get_map();
    maps.insert(pair<string,message::ptr>("systemid",string_message::create("123")));
    maps.insert(pair<string,message::ptr>("groupid",string_message::create("")));
    maps.insert(pair<string,message::ptr>("clientid",string_message::create("123")));
    maps.insert(pair<string,message::ptr>("accesstoken",string_message::create("")));
    maps.insert(pair<string,message::ptr>("time",string_message::create("")));
    _io->socket()->emitmessage("login",object_map_ptr);`
I do it like this, but server can not receive object message.

**Comment by liwuking** [comment]
@panhuachao  Can you solve it
