### ISSUE TITLE
How to make a response?

### ISSUE THREAD

**Issue by eternaltao** [socketio/socket.io-client-cpp#75]
Hello, @melode11 

I want to make a response when recevied a message by current_socket->on("message",xxxx)
But I don't know how to use the two parameters below:
bool isAck,
message::list &ack_resp

~~~
current_socket->on("message", sio::socket::event_listener_aux([&](string const& name, message::ptr const& data, bool isAck,message::list &ack_resp)
        {
              _lock.lock();
              string devices = data->get_map()["devices"]->get_string();
              string message = data->get_map()["message"]->get_string();
              EM(message);
              _lock.unlock();
        }));
~~~

**Comment by nskondratev** [comment]
Hello, @eternaltao 

How did you manage to make a response with ack_resp argument?

Thank you for the answer in advance!
