### ISSUE TITLE
iOS: Event on connected occurs after view disappeared cause crash

### ISSUE THREAD

**Issue by nhandl3** [socketio/socket.io-client-cpp#77]
Hi guys, thank you for this library, it helps reduces my app size much on iOS.
However, I have a trouble when: 
In a view > connect > leave the view immediately > crash

I already added following cleanup code:

```
-(void)viewWillDisappear:(BOOL)animated
{
    _io->socket()->off_all();
    _io->set_open_listener(nullptr); // or _io->clear_con_listeners();
    _io->set_close_listener(nullptr);
    _io->close();
}
```

But the connect event handler still be called and causes BAD ACCESS error:

```
void OnConnected(CFTypeRef ctrl,std::string nsp)
{
    dispatch_async(dispatch_get_main_queue(), ^{
        [((__bridge CRViewController*)ctrl) onConnected]; //ctrl is bad access
    });
}
```

I want to ask why `clear_con_listeners` not work and which is best solution for this problem.
Thank you so much.

**Comment by melode11** [comment]
Maybe it is the ObjC code issue.
Even OnConnected is called earlier than viewWillDisappear, The code inside the dispatch_async may later than viewWillDisappear calls.
You can trying to retain your controller before convert it to CFTypeRef by using CFBridgeRetain() conversion.
