### ISSUE TITLE
Cmake windows VS2015 

### ISSUE THREAD

**Issue by derofim** [socketio/socket.io-client-cpp#81]
Under windows 10 compiled boost 1.60
With Cmake got VS15 solution.
* Issue: Same error as http://stackoverflow.com/questions/32969289/error-in-websocketpp-library-and-boost-in-windows-visual-studio-2015
( UPD: Defining _WEBSOCKETPP_NOEXCEPT_ and _WEBSOCKETPP_CPP11_CHRONO_ under Project Settings -> C/C++ -> Preprocessor -> Preprocessor definitions successfully compiled socket.io-client-cpp debug .lib files)

Created simple sample program
main.cpp: https://gist.github.com/derofim/df87901b386a2703fb26#file-main-cpp 
server: https://gist.github.com/derofim/df87901b386a2703fb26#file-index-js
Its works, but code like
```
void OnMessage(sio::event &){}
// ...
h.socket()->on("new message", &OnMessage);
```
dont work:
* Issue: Compiler Error C2668 ambiguous call to overloaded function  sio::socket::on

UPD: code (like below) works:
```
	h.socket()->on("new message", sio::socket::event_listener([&](event& event)
	{
		cout << "OnMessage!!!" << endl;
	}));
```

**Comment by melode11** [comment]
It is a windows compiler issue, if you want use a function as the listener, remember to explicitly create  a `sio::socket::event_listener` from the function or cast that function to `sio::socket::event_listener` .
