### ISSUE TITLE
compile under MacOS with clang

### ISSUE THREAD

**Issue by rodolfoamarques** [socketio/socket.io-client-cpp#90]
I wanted to try out the lib and just made a simple program to test how to include it and use it but I am not being able to figure how to do it.

I installed boost through homebrew, cloned the repository and built it with no problems. Then I created a simple main.cpp inside the build directory with the following code:
```
#include <iostream>
#include <sio_client.h>

int main( int argc, char** argv ) {
	sio::client h;
	h.connect("http://127.0.0.1:3000");
	return 0;
}
```

I tried to compile it with
`clang++ -Iinclude -Llib/Release -llibsioclient main.cpp`

but it gives me an error:
```
ld: library not found for -llibsioclient
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Could you please point me in the right direction here? Thanks!

**Comment by melode11** [comment]
should be -lsioclient, not lib prefix.

**Comment by rodolfoamarques** [comment]
Thanks a lot! that fixed it. Sorry for the dumb mistake!
