### ISSUE TITLE
error: websocketpp/client.hpp: No such file or directory  #include <websocketpp/client.hpp> 

### ISSUE THREAD

**Issue by panhuachao** [socketio/socket.io-client-cpp#94]
I'm a newer to learn qt. I want to use qt for realizing socket.io of nodejs。When I include this projects according to http://socket.io/blog/socket-io-cpp/ , I found the error “error: websocketpp/client.hpp: No such file or directory  #include <websocketpp/client.hpp> ”. Can you help me? Thanks a lot.

**Comment by melode11** [comment]
When you clone, remember to clone with `git clone --recurse-submodules https://github.com/socketio/socket.io-client-cpp.git`

**Comment by panhuachao** [comment]
Thanks a lot.At first I didn't use to clone, and just downloaded it, and then I also downloaded rapidjson and  websocketpp projects, which worked well.

**Comment by yulyu2008** [comment]
I have encountered this problem, are you solved?

**Comment by sleoniy** [comment]
Bump, dont have access to clone external repos

**Comment by pha377** [comment]
I have a similar problem.

When building the project, 
it doesn't recognize #include <websocketpp/client.hpp>
but it does with #include "websocketpp/client.hpp"

Also as #include <websocketpp/client.hpp> the IDE doesn't recognize it, so it show me hundreds of errors.

I managed to solve it once but, I don't remember how?
Anyone?
