### ISSUE TITLE
Connecting with "wss://"

### ISSUE THREAD

**Issue by nwestbury** [socketio/socket.io-client-cpp#95]
I've compiled the library successfully and connecting to the localhost with "ws://" URI works fine.

But when I try to connect to the external server (which uses encryption) "wss://" fails with the following:

`[2016-05-08 17:07:27] [connect] Successful connection`
`[2016-05-08 17:07:28] [error] handle_read_http_response error: websocketpp.transport:7 (End of File)`

What are the steps I need to take in order to connect to a server with TLS encryption? Thanks!

**Comment by melode11** [comment]
You need to recompile the lib with SIO_TLS macro to make it a secured socket.io client.

**Comment by nwestbury** [comment]
Thanks for the reply reply but could you show me how? I've tried `make CXX-flags=-DSIO_TLS` to no avail
